service: "structure-flow"

custom:
  apiGatewayCaching:
    enabled: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs18.x
  region: eu-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
          Resource:
            - arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/structure-flow/*

  environment:
    NODE_OPTIONS: "--enable-source-maps"
    CONFIG_REGION: ${self:provider.region}

functions:
  createCompany:
    name: structreFlowCreateCompany-${self:provider.stage}
    handler: ./src/handlers/createCompany/index.handler
    events:
      - http:
          path: /company
          method: POST
          cors: true

  addCompanyUser:
    name: structreFlowaddCompanyUser-${self:provider.stage}
    handler: ./src/handlers/addCompanyUser/index.handler
    events:
      - http:
          path: /company/user
          method: POST
          cors: true

  getCompany:
    name: structreFlowGetCompany-${self:provider.stage}
    handler: ./src/handlers/getCompany/index.handler
    events:
      - http:
          path: /company
          method: GET
          cors: true

  removeCompanyUser:
    name: structreFlowremoveCompanyUser-${self:provider.stage}
    handler: ./src/handlers/removeCompanyUser/index.handler
    events:
      - http:
          path: /company/user
          method: DELETE
          cors: true
